HakanERP/Controllers/MusteriController.cs
using HakanERP.Models;
using NZF_DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml;
using System.Xml.Linq;
using Excel = Microsoft.Office.Interop.Excel;

namespace HakanERP.Controllers
{
    public class MusteriController : Controller
    {
        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase excelFile)
        {

            if (excelFile == null
            || excelFile.ContentLength == 0)
            {
                ViewBag.Error = "Lütfen dosya seçimi yapınız.";

                return RedirectToAction("Index");
            }
            else
            {

                if (excelFile.FileName.EndsWith("xls")
                || excelFile.FileName.EndsWith("xlsx"))
                {

                    string path = Server.MapPath("~/Content/" + excelFile.FileName);

                    //Dosya kontrol edilir, varsa silinir.
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    //Excel path altına kaydedilir.
                    excelFile.SaveAs(path);

                    //+Exceli açıyoruz
                    Excel.Application application = new Excel.Application();
                    Excel.Workbook workbook = application.Workbooks.Open(path);
                    Excel.Worksheet worksheet = workbook.ActiveSheet;
                    Excel.Range range = worksheet.UsedRange;
                    //-


                    List<MusterilerModel> localList = new List<MusterilerModel>();
                    for (int i = 2; i <= range.Rows.Count; i++)
                    {
                        List<TurMusModel> tmmm = new List<TurMusModel>();
                        DateTime dt = Convert.ToDateTime(((Excel.Range)range.Cells[i, 2]).Text);
                        string dt1 = dt.ToString("yyyy-MM-dd");
                        string sql = "  Select * from Turlar where BaslangicTarihi='" + dt1 + "'";
                        DataAccesBase db = new DataAccesBase();
                        DataTable model = db.ReturnDataTable(sql);
                        int MusID, TurID;
                        foreach (DataRow item in model.Rows)
                        {

                            string sqll = "select * from Musteriler where TcNo='" + ((Excel.Range)range.Cells[i, 10]).Text + "'";
                            if (sqll != "")
                            {
                                DataAccesBase dbb = new DataAccesBase();
                                DataTable modell = dbb.ReturnDataTable(sqll);

                                foreach (DataRow itemm in modell.Rows)
                                {
                                    MusID = (int)itemm["ID"];
                                    TurID = (int)item["ID"];
                                    TurMus tm = new TurMus();
                                    tm.MusteriID = MusID;
                                    tm.TurID = TurID;
                                    tm.PersonelID = 1008;
                                    tm.Kaydet();

                                }
                            }
                            else
                            {
                                TurMus tm = new TurMus();
                                tm.MusteriID = 1;
                                tm.TurID = 1;
                                tm.PersonelID = 1008;
                                tm.Kaydet();

                            }

                        }

                    }

                    application.Quit();


                    ViewBag.ListDetay = localList;

                    return View("Listele");
                }
                else
                {
                    ViewBag.Error = "Dosya tipiniz yanlış, lütfen '.xls' yada '.xlsx' uzantılı dosya yükleyiniz.";

                    return View();
                }
            }
        }

        public ActionResult Index()
        {

            if (Session["KullaniciAdi"] != null)
            {


                List<MusterilerModel> MusteriList = new List<MusterilerModel>();
                string sql;
                DataAccesBase db = new DataAccesBase();
                sql = "Select * from Musteriler order by ID desc";
                DataTable model = db.ReturnDataTable(sql);
                foreach (DataRow item in model.Rows)
                {
                    MusteriList.Add(new MusterilerModel
                    {
                        ID = Convert.ToInt32(item["ID"]),
                        Ad = item["Ad"].ToString(),
                        Soyad = item["Soyad"].ToString(),
                        TcNo = item["TcNo"].ToString(),
                        Telefon = item["Telefon"].ToString(),
                        EPosta = item["EPosta"].ToString(),

                        EklendigiTarih = (DateTime)item["EklendigiTarih"]

                    });
                }


                return View(MusteriList);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult Ekle()
        {
            if (Session["KullaniciAdi"] != null)
            {
                List<UlkelerModel> ulkeler = new List<Models.UlkelerModel>();
                string sql = "Select * from Ulkeler as u left join Musteriler as m on u.UlkeAdi = m.Ulke";
                DataAccesBase db = new DataAccesBase();
                DataTable model = db.ReturnDataTable(sql);
                foreach (DataRow item in model.Rows)
                {
                    ulkeler.Add(new UlkelerModel
                    {
                        UlkeId = (int)item["UlkeId"],
                        UlkeAdi = item["UlkeAdi"].ToString()
                    });
                }

                ViewBag.Ulke = ulkeler;

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult Ekle(MusterilerModel m, int ID = 0)
        {

            List<UlkelerModel> ulkeler = new List<Models.UlkelerModel>();
            string sqls = "Select * from Ulkeler as u left join Musteriler as m on u.UlkeAdi = m.Ulke";
            DataAccesBase dbs = new DataAccesBase();
            DataTable models = dbs.ReturnDataTable(sqls);
            foreach (DataRow item in models.Rows)
            {
                ulkeler.Add(new UlkelerModel
                {
                    UlkeId = (int)item["UlkeId"],
                    UlkeAdi = item["UlkeAdi"].ToString()
                });
            }

            ViewBag.Ulke = ulkeler;

            if (ID == 0)
            {
                string sql = "Select * from Musteriler as m left join Ulkeler as u on m.Ulke=u.UlkeId where m.TcNo='" + m.TcNo + "'";
                DataAccesBase db = new DataAccesBase();
                DataTable model = db.ReturnDataTable(sql);
                if (model.Rows.Count == 0)
                {
                    Musteriler mus = new Musteriler(m.ID);

                    mus.Ad = m.Ad;
                    string Ad = mus.Ad.ToUpper();
                    mus.Ad = karakterCevir(Ad);

                    mus.Adres = m.Adres;
                    if (mus.Adres != null)
                    {
                        string Adres = mus.Adres.ToUpper();
                        mus.Adres = karakterCevir(Adres);

                    }



                    mus.DogumTarihi = Convert.ToDateTime(m.DogumTarihi);
                    mus.EPosta = m.EPosta;
                    mus.Fax = m.Fax;
                    mus.GSM = m.GSM;
                    mus.PasapartNo = m.PasapartNo;

                    mus.Soyad = m.Soyad;
                    string Soyad = mus.Soyad.ToUpper();
                    mus.Soyad = karakterCevir(Soyad);

                    mus.TcNo = m.TcNo;
                    mus.Telefon = m.Telefon;

                    mus.Unvan = m.Unvan;
                    if (mus.Unvan != null)
                    {
                        string Unvan = mus.Unvan.ToUpper();
                        mus.Unvan = karakterCevir(Unvan);

                    }

                    mus.VergiDairesi = m.VergiDairesi;
                    if (mus.VergiDairesi != null)
                    {
                        string VergiDairesi = mus.VergiDairesi.ToUpper();
                        mus.VergiDairesi = karakterCevir(VergiDairesi);


                    }
                    mus.VergiNo = m.VergiNo;
                    mus.Ulke = m.Ulke;
                    mus.Yas = m.Yas;
                    mus.Yas = ((DateTime.Now.Year) - (mus.DogumTarihi.Year));

                    mus.PasaportBitisTarihi = m.PasaportBitisTarihi;

                    mus.RezNo = m.RezNo;
                    mus.Cinsiyet = m.Cinsiyet;

                    mus.EklendigiTarih = m.EklendigiTarih;
                    mus.EklendigiTarih = DateTime.Now;
                    mus.EkleyenPersonel = m.EkleyenPersonel;
                    mus.EkleyenPersonel = Session["PersonelAd"].ToString().ToUpper() + " " + Session["PersonelSoyAd"].ToString().ToUpper();

                    mus.Kaydet();
                    Response.Write("<script language='javascript'>alert('Kayıt Başarıyla Eklendi.');</script>");


                    return View();
                }
                else
                {
                    Response.Write("<script>alert('Böyle bir T.C numarası Mevcut. Lütfen Kimlik numaranızı kontrol edin')</script>");
                    return View();
                }

            }
            else
            {

HakanERP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HakanERP</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/deneme.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
    @*<link href="~/Content/DataTable.css" rel="stylesheet" type="text/css"/>*@
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    @*<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">*@
    <script src="~/scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="~/scripts/deneme.js" type="text/javascript"></script>
    @*<script src="~/scripts/DataTable.js" type="text/javascript"></script>*@
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="~/Scripts/modernizr-2.6.2.js" type="text/javascript"></script>

    <style>
        .dropbtn {
            background-color: #e32124;
            color: white;
            padding: 18px;
            font-size: 16px;
            border: none;
            cursor: pointer;
            border-radius: 100%;
        }

        .dropdown {
            position: fixed;
            margin-left: 400px;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            right: 0;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            transition: 0.48s;
            background-color: #600808;
            color: white;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                @Html.ActionLink("Müşteriler", "Index", "Musteri", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Turlar", "Index", "Tutar", new { area = "" }, new { @class = "navbar-brand", style = "margin-left:18px;" })
                @Html.ActionLink("Personeller", "Index", "Personel", new { area = "" }, new { @class = "navbar-brand", style = "margin-left:18px;" })
                @Html.ActionLink("Mail Gönder", "Filtrele", "Musteri", new { area = "" }, new { @class = "navbar-brand", style = "margin-left:18px;" })

                <div class="dropdown">
                    <button class="dropbtn">
                        @Session["BasHarfler"]
                    </button>
                    <div class="dropdown-content">
                        <a>@Session["PersonelAd"].ToString().ToUpper()&nbsp;@Session["PersonelSoyAd"].ToString().ToUpper()</a>
                        <a href="~/Login/Index"><i class="far fa-arrow-alt-circle-left"></i>&nbsp;ÇIKIŞ</a>
                    </div>

                </div>
            </div>
           
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tüm Hakları Saklıdır</p>
        </footer>
    </div>






</body>
</html>